# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-06-25 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoTrabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres_empleado', models.CharField(max_length=50)),
                ('apellidos_empleado', models.CharField(max_length=100)),
                ('cedula_empleado', models.CharField(max_length=11)),
                ('cedula_empleador', models.CharField(max_length=11)),
                ('domicilio_empleado', models.CharField(max_length=50)),
                ('fecha_nacimiento_empleado', models.DateField()),
                ('fecha_nacimiento_empleador', models.DateField()),
                ('lugar_nacimiento_empleado', models.CharField(max_length=50)),
                ('lugar_nacimiento_empleador', models.CharField(max_length=50)),
                ('cargo_empleado', models.CharField(max_length=40)),
                ('fecha_contratacion_empleado', models.DateField()),
                ('salario_empleado', models.FloatField()),
                ('smlmv', models.IntegerField()),
                ('smlmv_letra', models.CharField(max_length=50)),
                ('salario_letras_empleado', models.CharField(max_length=100)),
                ('nombre_empleador', models.CharField(max_length=50)),
                ('nombre_representante', models.CharField(max_length=50)),
                ('cedula_representante', models.CharField(max_length=11)),
                ('nit_empleador', models.CharField(max_length=20)),
                ('domicilio_empleador', models.CharField(max_length=50)),
                ('naturaleza_empleador', models.CharField(max_length=50)),
                ('objeto_social_empleador', models.CharField(max_length=50)),
                ('funciones_empleado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoEmpleador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='contratotrabajo',
            name='tipo_empleador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contrato_trabajo.TipoEmpleador'),
        ),
    ]
