from django import forms 
from blog.contrato_servicios.models import Document_contrato

class ServicioForm1(forms.ModelForm):
    
    class Meta:
        model=Document_contrato

        fields = [
            'Razon_social_juridica',
            'Nit_juridica',
            'Nombre_representante',
            'Cedula_representate',
            'Nombre_natural',
            'Cedula_contratista',
            'Ciudad_contratista',
            'Fecha_nacimiento_contratista',
            'Lugar_nacimiento_contratista',
            'Actividad_profesional_contratista',
            'Objeto_social_contratante',
            'Finalidad',
            'Servicio_manera_general',
            'Servicio_prestado_contratista',
            'Paragrafo_primero',
            'Contraprestacion_numeros',
            'Plazo_sugerido_dias',
            'Banco',
            'Tipo_cuenta',
            'Numero_cuenta',
            'Nombre_titular',
            'Cedula_titular',
            'Tipo_con',
            'Anos_meses',
            'Duracion_numeros',
            'Paragrafo_prueba_opcional',
            'Dias_prueba_numeros',
            'Fecha_prueba',
            'Direccion_Fisica_contratante',
            'Correo_electronico_contratante',


        ] 
 
        labels = {

            'Razon_social_juridica': 'Nombre de persona jurídica contratante',
            'Nit_juridica': 'NIT de la persona jurídica contratante',
            'Nombre_representante': 'Nombre completo del representante legal del contratante',
            'Cedula_representate': 'Cédula del representante legal del contratante',
            'Nombre_natural': 'Nombre completo de persona natural contratista',
            'Cedula_contratista': 'Cédula de la persona natural contratista',
            'Ciudad_contratista': 'Ciudad donde reside la persona natural contratista',
            'Fecha_nacimiento_contratista': 'Fecha de nacimiento de la persona natural contratista',
            'Lugar_nacimiento_contratista': 'Lugar de nacimiento de la persona natural contratista',
            'Actividad_profesional_contratista': 'Actividad profesional del contratista ',
            'Objeto_social_contratante': 'Objeto social del contratante' ,
            'Finalidad': 'Servicio que el contratante busca en el contratista',
            'Servicio_manera_general': 'Servicio de manera general',
            'Servicio_prestado_contratista': 'Servicios prestados por el contratista',
            'Paragrafo_primero': '¿Desea incluir paragrafo primero de clausulas?',
            'Contraprestacion_numeros': 'Contraprestación',
            'Plazo_sugerido_dias': 'Días de plazo(Plazo sugerido 5 Días)',
            'Banco': 'Banco',
            'Tipo_cuenta': 'Tipo de cuenta',
            'Numero_cuenta': 'Número de cuenta',
            'Nombre_titular': 'Nombre del titular',
            'Cedula_titular': 'Cédula del titular',
            'Tipo_con': 'Gastos de ejecución:',
            'Anos_meses': 'Duracion en años o meses:',
            'Duracion_numeros': 'Duración del contrato',
            'Paragrafo_prueba_opcional': '¿Desea incluir paragrafo primero de duración de contrato?',
            'Dias_prueba_numeros': 'Periodo de prueba en días',
            'Fecha_prueba': 'Fecha donde se inicia la prueba',
            'Direccion_Fisica_contratante': 'Direccion Física del contratante',
            'Correo_electronico_contratante': 'Dirección electronica del contratante',

        }

        widgets = {
            'Razon_social_juridica': forms.TextInput(attrs={'class': 'form-control'}),
            'Nit_juridica': forms.TextInput(attrs={'class': 'form-control'}),
            'Nombre_representante': forms.TextInput(attrs={'class': 'form-control'}),
            'Cedula_representate': forms.TextInput(attrs={'class': 'form-control'}),
            'Nombre_natural': forms.TextInput(attrs={'class': 'form-control'}),
            'Cedula_contratista': forms.TextInput(attrs={'class': 'form-control'}),
            'Ciudad_contratista': forms.TextInput(attrs={'class': 'form-control'}),
            'Fecha_nacimiento_contratista': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Fecha', 'type': 'date'}),
            'Lugar_nacimiento_contratista': forms.TextInput(attrs={'class': 'form-control'}),
            'Actividad_profesional_contratista': forms.TextInput(attrs={'class': 'form-control'}),
            'Objeto_social_contratante': forms.TextInput(attrs={'class': 'form-control', 'rows': '2'}),
            'Finalidad': forms.TextInput(attrs={'class': 'form-control'}),
            'Servicio_manera_general': forms.TextInput(attrs={'class': 'form-control'}),
            'Servicio_prestado_contratista': forms.Textarea(attrs={'class': 'form-control', 'rows': "2",}),
            'Paragrafo_primero': forms.CheckboxInput(),
            'Contraprestacion_numeros': forms.TextInput(attrs={'class': 'form-control'}),
            'Plazo_sugerido_dias': forms.TextInput(attrs={'class': 'form-control'}),
            'Banco': forms.TextInput(attrs={'class': 'form-control'}),
            'Tipo_cuenta': forms.TextInput(attrs={'class': 'form-control'}),
            'Numero_cuenta': forms.TextInput(attrs={'class': 'form-control'}),
            'Nombre_titular': forms.TextInput(attrs={'class': 'form-control'}),
            'Cedula_titular': forms.TextInput(attrs={'class': 'form-control'}),
            'Tipo_con': forms.Select(attrs={'class': 'form-control'}),
            'Anos_meses': forms.Select(attrs={'class': 'form-control'}),
            'Duracion_numeros': forms.TextInput(attrs={'class': 'form-control'}),
            'Paragrafo_prueba_opcional': forms.CheckboxInput(),
            'Dias_prueba_numeros': forms.TextInput(attrs={'class': 'test  form-control'}),
            'Fecha_prueba': forms.DateInput(attrs={'class': 'test form-control', 'placeholder': 'Fecha', 'type': 'date'}),
            'Direccion_Fisica_contratante': forms.TextInput(attrs={'class': 'form-control'}),
            'Correo_electronico_contratante': forms.EmailInput(attrs={'class': 'form-control'}),
            
        }

class ServicioForm2(forms.ModelForm):
        
    class Meta:
        model=Document_contrato

        fields = [
            'Razon_social_juridica',
            'Nit_juridica',
            'Nombre_representante',
            'Cedula_representate',
            'Razon_social_juridica_contratista',
            'Nit_juridica_contratista',
            'Nombre_representante_contratista',
            'Cedula_representate_contratista',
            'Actividad_profesional_contratista',
            'Objeto_social_contratante',
            'Finalidad',
            'Servicio_manera_general',
            'Servicio_prestado_contratista',
            'Paragrafo_primero',
            'Contraprestacion_numeros',
            'Plazo_sugerido_dias',
            'Banco',
            'Tipo_cuenta',
            'Numero_cuenta',
            'Nombre_titular',
            'Cedula_titular',
            'Tipo_con',
            'Anos_meses',
            'Duracion_numeros',
            'Paragrafo_prueba_opcional',
            'Dias_prueba_numeros',
            'Fecha_prueba',
            'Direccion_Fisica_contratante',
            'Correo_electronico_contratante',


        ] 
 
        labels = {

            'Razon_social_juridica': 'Nombre de persona jurídica contratante',
            'Nit_juridica': 'NIT de la persona jurídica contratante',
            'Nombre_representante': 'Nombre completo del representante legal del contratante',
            'Cedula_representate': 'Cédula del representante legal del contratante',
            'Razon_social_juridica_contratista': 'Nombre de persona jurídica contratista',
            'Nit_juridica_contratista': 'NIT de la persona jurídica contratista',
            'Nombre_representante_contratista': 'Nombre completo del representante legal del contratista',
            'Cedula_representate_contratista': 'Cédula del representante legal del contratista',
            'Actividad_profesional_contratista': 'Actividad profesional del contratista ',
            'Objeto_social_contratante': 'Objeto social del contratante' ,
            'Finalidad': 'Servicio que el contratante busca en el contratista',
            'Servicio_manera_general': 'Servicio de manera general',
            'Servicio_prestado_contratista': 'Servicios prestados por el contratista',
            'Paragrafo_primero': '¿Desea incluir paragrafo primero de clausulas?',
            'Contraprestacion_numeros': 'Contraprestación',
            'Plazo_sugerido_dias': 'Días de plazo(Plazo sugerido 5 Días)',
            'Banco': 'Banco',
            'Tipo_cuenta': 'Tipo de cuenta',
            'Numero_cuenta': 'Número de cuenta',
            'Nombre_titular': 'Nombre del titular',
            'Cedula_titular': 'Cédula del titular',
            'Tipo_con': 'Gastos de ejecución:',
            'Anos_meses': 'Duracion en años o meses:',
            'Duracion_numeros': 'Duración del contrato',
            'Paragrafo_prueba_opcional': '¿Desea incluir paragrafo primero de duración de contrato?',
            'Dias_prueba_numeros': 'Periodo de prueba en días',
            'Fecha_prueba': 'Fecha donde se inicia la prueba',
            'Direccion_Fisica_contratante': 'Direccion Física del contratante',
            'Correo_electronico_contratante': 'Dirección electronica del contratante',

        }

        widgets = {
            'Razon_social_juridica': forms.TextInput(attrs={'class': 'form-control'}),
            'Nit_juridica': forms.TextInput(attrs={'class': 'form-control'}),
            'Nombre_representante': forms.TextInput(attrs={'class': 'form-control'}),
            'Cedula_representate': forms.TextInput(attrs={'class': 'form-control'}),
            'Razon_social_juridica_contratista': forms.TextInput(attrs={'class': 'form-control'}),
            'Nit_juridica_contratista': forms.TextInput(attrs={'class': 'form-control'}),
            'Nombre_representante_contratista': forms.TextInput(attrs={'class': 'form-control'}),
            'Cedula_representate_contratista': forms.TextInput(attrs={'class': 'form-control'}),
            'Actividad_profesional_contratista': forms.TextInput(attrs={'class': 'form-control'}),
            'Objeto_social_contratante': forms.TextInput(attrs={'class': 'form-control'}),
            'Finalidad': forms.TextInput(attrs={'class': 'form-control'}),
            'Servicio_manera_general': forms.TextInput(attrs={'class': 'form-control'}),
            'Servicio_prestado_contratista': forms.Textarea(attrs={'class': 'form-control', 'rows': "2",}),
            'Paragrafo_primero': forms.CheckboxInput(),
            'Contraprestacion_numeros': forms.TextInput(attrs={'class': 'form-control'}),
            'Plazo_sugerido_dias': forms.TextInput(attrs={'class': 'form-control'}),
            'Banco': forms.TextInput(attrs={'class': 'form-control'}),
            'Tipo_cuenta': forms.TextInput(attrs={'class': 'form-control'}),
            'Numero_cuenta': forms.TextInput(attrs={'class': 'form-control'}),
            'Nombre_titular': forms.TextInput(attrs={'class': 'form-control'}),
            'Cedula_titular': forms.TextInput(attrs={'class': 'form-control'}),
            'Tipo_con': forms.Select(attrs={'class': 'form-control'}),
            'Anos_meses': forms.Select(attrs={'class': 'form-control'}),
            'Duracion_numeros': forms.TextInput(attrs={'class': 'form-control'}),
            'Paragrafo_prueba_opcional': forms.CheckboxInput(),
            'Dias_prueba_numeros': forms.TextInput(attrs={'class': 'test  form-control'}),
            'Fecha_prueba': forms.DateInput(attrs={'class': 'test form-control', 'placeholder': 'Fecha', 'type': 'date'}),
            'Direccion_Fisica_contratante': forms.TextInput(attrs={'class': 'form-control'}),
            'Correo_electronico_contratante': forms.EmailInput(attrs={'class': 'form-control'}),
            
        }

class ServicioForm3(forms.ModelForm):
            
    class Meta:
        model=Document_contrato

        fields = [
            'Razon_social_natural',
            'Cedula_contratante_natural',
            'Ciudad_contratante_natural',
            'Fecha_nacimiento_contratante_natural',
            'Lugar_nacimiento_contratante_natural',
            'Razon_social_juridica_contratista',
            'Nit_juridica_contratista',
            'Nombre_representante_contratista',
            'Cedula_representate_contratista',
            'Actividad_profesional_contratista',
            'Objeto_social_contratante',
            'Finalidad',
            'Servicio_manera_general',
            'Servicio_prestado_contratista',
            'Paragrafo_primero',
            'Contraprestacion_numeros',
            'Plazo_sugerido_dias',
            'Banco',
            'Tipo_cuenta',
            'Numero_cuenta',
            'Nombre_titular',
            'Cedula_titular',
            'Tipo_con',
            'Anos_meses',
            'Duracion_numeros',
            'Paragrafo_prueba_opcional',
            'Dias_prueba_numeros',
            'Fecha_prueba',
            'Direccion_Fisica_contratante',
            'Correo_electronico_contratante',


        ] 
 
        labels = {

            'Razon_social_natural': 'Nombre de persona natural contratante',
            'Cedula_contratante_natural': 'Cédula de la persona natural contratante',
            'Ciudad_contratante_natural': 'Ciudad donde reside la persona natural contratante',
            'Fecha_nacimiento_contratante_natural': 'Fecha de nacimiento de la persona natural contratante',
            'Lugar_nacimiento_contratante_natural': 'Lugar de nacimiento de la persona natural contratante',
            'Razon_social_juridica_contratista': 'Nombre de persona jurídica contratista',
            'Nit_juridica_contratista': 'NIT de la persona jurídica contratista',
            'Nombre_representante_contratista': 'Nombre completo del representante legal del contratista',
            'Cedula_representate_contratista': 'Cédula del representante legal del contratista',
            'Actividad_profesional_contratista': 'Actividad profesional del contratista ',
            'Objeto_social_contratante': 'Objeto social del contratante' ,
            'Finalidad': 'Servicio que el contratante busca en el contratista',
            'Servicio_manera_general': 'Servicio de manera general',
            'Servicio_prestado_contratista': 'Servicios prestados por el contratista',
            'Paragrafo_primero': '¿Desea incluir paragrafo primero de clausulas?',
            'Contraprestacion_numeros': 'Contraprestación',
            'Plazo_sugerido_dias': 'Días de plazo(Plazo sugerido 5 Días)',
            'Banco': 'Banco',
            'Tipo_cuenta': 'Tipo de cuenta',
            'Numero_cuenta': 'Número de cuenta',
            'Nombre_titular': 'Nombre del titular',
            'Cedula_titular': 'Cédula del titular',
            'Tipo_con': 'Gastos de ejecución:',
            'Anos_meses': 'Duracion en años o meses:',
            'Duracion_numeros': 'Duración del contrato',
            'Paragrafo_prueba_opcional': '¿Desea incluir paragrafo primero de duración de contrato?',
            'Dias_prueba_numeros': 'Periodo de prueba en días',
            'Fecha_prueba': 'Fecha donde se inicia la prueba',
            'Direccion_Fisica_contratante': 'Direccion Física del contratante',
            'Correo_electronico_contratante': 'Dirección electronica del contratante',

        }

        widgets = {
            'Razon_social_natural': forms.TextInput(attrs={'class': 'form-control'}),
            'Cedula_contratante_natural': forms.TextInput(attrs={'class': 'form-control'}),
            'Ciudad_contratante_natural': forms.TextInput(attrs={'class': 'form-control'}),
            'Fecha_nacimiento_contratante_natural': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Fecha', 'type': 'date'}),
            'Lugar_nacimiento_contratante_natural': forms.TextInput(attrs={'class': 'form-control'}),
            'Razon_social_juridica_contratista': forms.TextInput(attrs={'class': 'form-control'}),
            'Nit_juridica_contratista': forms.TextInput(attrs={'class': 'form-control'}),
            'Nombre_representante_contratista': forms.TextInput(attrs={'class': 'form-control'}),
            'Cedula_representate_contratista': forms.TextInput(attrs={'class': 'form-control'}),
            'Actividad_profesional_contratista': forms.TextInput(attrs={'class': 'form-control'}),
            'Objeto_social_contratante': forms.TextInput(attrs={'class': 'form-control', 'rows': '2'}),
            'Finalidad': forms.TextInput(attrs={'class': 'form-control'}),
            'Servicio_manera_general': forms.TextInput(attrs={'class': 'form-control'}),
            'Servicio_prestado_contratista': forms.Textarea(attrs={'class': 'form-control', 'rows': "2",}),
            'Paragrafo_primero': forms.CheckboxInput(),
            'Contraprestacion_numeros': forms.TextInput(attrs={'class': 'form-control'}),
            'Plazo_sugerido_dias': forms.TextInput(attrs={'class': 'form-control'}),
            'Banco': forms.TextInput(attrs={'class': 'form-control'}),
            'Tipo_cuenta': forms.TextInput(attrs={'class': 'form-control'}),
            'Numero_cuenta': forms.TextInput(attrs={'class': 'form-control'}),
            'Nombre_titular': forms.TextInput(attrs={'class': 'form-control'}),
            'Cedula_titular': forms.TextInput(attrs={'class': 'form-control'}),
            'Tipo_con': forms.Select(attrs={'class': 'form-control'}),
            'Anos_meses': forms.Select(attrs={'class': 'form-control'}),
            'Duracion_numeros': forms.TextInput(attrs={'class': 'form-control'}),
            'Paragrafo_prueba_opcional': forms.CheckboxInput(),
            'Dias_prueba_numeros': forms.TextInput(attrs={'class': 'test  form-control'}),
            'Fecha_prueba': forms.DateInput(attrs={'class': 'test form-control', 'placeholder': 'Fecha', 'type': 'date'}),
            'Direccion_Fisica_contratante': forms.TextInput(attrs={'class': 'form-control'}),
            'Correo_electronico_contratante': forms.EmailInput(attrs={'class': 'form-control'}),
            
        }

class ServicioForm4(forms.ModelForm):
            
    class Meta:
        model=Document_contrato

        fields = [
            'Razon_social_natural',
            'Cedula_contratante_natural',
            'Ciudad_contratante_natural',
            'Fecha_nacimiento_contratante_natural',
            'Lugar_nacimiento_contratante_natural',
    
            'Nombre_natural',
            'Cedula_contratista',
            'Ciudad_contratista',
            'Fecha_nacimiento_contratista',
            'Lugar_nacimiento_contratista',
            
            'Actividad_profesional_contratista',
            'Objeto_social_contratante',
            'Finalidad',
            'Servicio_manera_general',
            'Servicio_prestado_contratista',
            'Paragrafo_primero',
            'Contraprestacion_numeros',
            'Plazo_sugerido_dias',
            'Banco',
            'Tipo_cuenta',
            'Numero_cuenta',
            'Nombre_titular',
            'Cedula_titular',
            'Tipo_con',
            'Anos_meses',
            'Duracion_numeros',
            'Paragrafo_prueba_opcional',
            'Dias_prueba_numeros',
            'Fecha_prueba',
            'Direccion_Fisica_contratante',
            'Correo_electronico_contratante',


        ] 
 
        labels = {

            'Razon_social_natural': 'Nombre de persona natural contratante',
            'Cedula_contratante_natural': 'Cédula de la persona natural contratante',
            'Ciudad_contratante_natural': 'Ciudad donde reside la persona natural contratante',
            'Fecha_nacimiento_contratante_natural': 'Fecha de nacimiento de la persona natural contratante',
            'Lugar_nacimiento_contratante_natural': 'Lugar de nacimiento de la persona natural contratante',
            'Nombre_natural': 'Nombre completo de persona natural contratista',
            'Cedula_contratista': 'Cédula de la persona natural contratista',
            'Ciudad_contratista': 'Ciudad donde reside la persona natural contratista',
            'Fecha_nacimiento_contratista': 'Fecha de nacimiento de la persona natural contratista',
            'Lugar_nacimiento_contratista': 'Lugar de nacimiento de la persona natural contratista',

            'Actividad_profesional_contratista': 'Actividad profesional del contratista',
            'Objeto_social_contratante': 'Objeto social del contratante' ,
            'Finalidad': 'Servicio que el contratante busca en el contratista',
            'Servicio_manera_general': 'Servicio de manera general',
            'Servicio_prestado_contratista': 'Servicios prestados por el contratista',
            'Paragrafo_primero': '¿Desea incluir paragrafo primero de clausulas?',
            'Contraprestacion_numeros': 'Contraprestación',
            'Plazo_sugerido_dias': 'Días de plazo(Plazo sugerido 5 Días)',
            'Banco': 'Banco',
            'Tipo_cuenta': 'Tipo de cuenta',
            'Numero_cuenta': 'Número de cuenta',
            'Nombre_titular': 'Nombre del titular',
            'Cedula_titular': 'Cédula del titular',
            'Tipo_con': 'Gastos de ejecución:',
            'Anos_meses': 'Duracion en años o meses:',
            'Duracion_numeros': 'Duración del contrato',
            'Paragrafo_prueba_opcional': '¿Desea incluir paragrafo primero de duración de contrato?',
            'Dias_prueba_numeros': 'Periodo de prueba en días',
            'Fecha_prueba': 'Fecha donde se inicia la prueba',
            'Direccion_Fisica_contratante': 'Direccion Física del contratante',
            'Correo_electronico_contratante': 'Dirección electronica del contratante',

        }

        widgets = {
            'Razon_social_natural': forms.TextInput(attrs={'class': 'form-control'}),
            'Cedula_contratante_natural': forms.TextInput(attrs={'class': 'form-control'}),
            'Ciudad_contratante_natural': forms.TextInput(attrs={'class': 'form-control'}),
            'Fecha_nacimiento_contratante_natural': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Fecha', 'type': 'date'}),
            'Lugar_nacimiento_contratante_natural': forms.TextInput(attrs={'class': 'form-control'}),
            'Nombre_natural': forms.TextInput(attrs={'class': 'form-control'}),
            'Cedula_contratista': forms.TextInput(attrs={'class': 'form-control'}),
            'Ciudad_contratista': forms.TextInput(attrs={'class': 'form-control'}),
            'Fecha_nacimiento_contratista': forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Fecha', 'type': 'date'}),
            'Lugar_nacimiento_contratista': forms.TextInput(attrs={'class': 'form-control'}),
            'Actividad_profesional_contratista': forms.TextInput(attrs={'class': 'form-control'}),
            'Objeto_social_contratante': forms.TextInput(attrs={'class': 'form-control'}),
            'Finalidad': forms.TextInput(attrs={'class': 'form-control'}),
            'Servicio_manera_general': forms.TextInput(attrs={'class': 'form-control'}),
            'Servicio_prestado_contratista': forms.Textarea(attrs={'class': 'form-control', 'rows': "2",}),
            'Paragrafo_primero': forms.CheckboxInput(),
            'Contraprestacion_numeros': forms.TextInput(attrs={'class': 'form-control'}),
            'Plazo_sugerido_dias': forms.TextInput(attrs={'class': 'form-control'}),
            'Banco': forms.TextInput(attrs={'class': 'form-control'}),
            'Tipo_cuenta': forms.TextInput(attrs={'class': 'form-control'}),
            'Numero_cuenta': forms.TextInput(attrs={'class': 'form-control'}),
            'Nombre_titular': forms.TextInput(attrs={'class': 'form-control'}),
            'Cedula_titular': forms.TextInput(attrs={'class': 'form-control'}),
            'Tipo_con': forms.Select(attrs={'class': 'form-control'}),
            'Anos_meses': forms.Select(attrs={'class': 'form-control'}),
            'Duracion_numeros': forms.TextInput(attrs={'class': 'form-control'}),
            'Paragrafo_prueba_opcional': forms.CheckboxInput(),
            'Dias_prueba_numeros': forms.TextInput(attrs={'class': 'test  form-control'}),
            'Fecha_prueba': forms.DateInput(attrs={'class': 'test form-control', 'placeholder': 'Fecha', 'type': 'date'}),
            'Direccion_Fisica_contratante': forms.TextInput(attrs={'class': 'form-control'}),
            'Correo_electronico_contratante': forms.EmailInput(attrs={'class': 'form-control'}),
        }