# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-06-25 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document_Acuerdo_Confidencialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_natural', models.CharField(max_length=50, null=True)),
                ('Cedula_natural', models.CharField(max_length=50, null=True)),
                ('Nombre_representante_titular', models.CharField(max_length=100)),
                ('Cedula_representante_titular', models.CharField(max_length=12)),
                ('Razon_social_titular', models.CharField(max_length=50)),
                ('Sociedadt', models.CharField(max_length=50)),
                ('Nit_titular', models.CharField(max_length=30)),
                ('Nombre_representante_receptor', models.CharField(max_length=100)),
                ('Cedula_representante_receptor', models.CharField(max_length=12)),
                ('Razon_social_receptor', models.CharField(max_length=50)),
                ('Nit_receptor', models.CharField(max_length=30)),
                ('Persona', models.CharField(max_length=40)),
                ('Consideracion_adicional', models.TextField()),
                ('Salario', models.CharField(max_length=40)),
                ('Salario_en_numeros', models.DecimalField(decimal_places=10, max_digits=20)),
                ('Direccion_titular', models.CharField(max_length=50)),
                ('Telefono_titular', models.CharField(max_length=30)),
                ('Email_titular', models.EmailField(max_length=254)),
                ('Direccion_receptor', models.CharField(max_length=50)),
                ('Telefono_receptor', models.CharField(max_length=30)),
                ('Email_receptor', models.EmailField(max_length=254)),
                ('Fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_persona', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sociedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_sociedad', models.CharField(max_length=40)),
            ],
        ),
    ]
